import { FORMATION_LAYOUTS, TACTIC_OPTIONS, assignPlayersToFormation } from './matchday-engine-v0431.js?v=0.4.3.1';

const SAVE_KEY='flm-career-save', STYLE_ID='flm-v044-career-style', VERSION='V0.4.4';
let cachedDb=null, renderQueued=false;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const clean=v=>String(v||'').toUpperCase().replaceAll(' ','');
const manager=()=>window.FLMManager;
const career=()=>manager()?.activeCareer||null;
const db=async()=>cachedDb||=(await manager().loadDatabase());
const playerById=(database,id)=>database.players.find(p=>p.id===id);
const displayName=p=>{const first=String(p?.firstName||'').trim(),last=String(p?.lastName||'').trim();return first&&last?`${first} ${last}`:String(p?.name||'').replace(',', '').trim();};

function persist(c){c.updatedAt=new Date().toISOString();localStorage.setItem(SAVE_KEY,JSON.stringify(c));const s=document.querySelector('[data-career-save-status]');if(s)s.textContent='SAVED';}
function rerender(tab){requestAnimationFrame(()=>document.querySelector(`[data-career-tab="${tab}"]`)?.click());}
function preferredPositions(p){return [p?.primaryPosition].filter(Boolean);}
function alternativePositions(p){return [...new Set((p?.secondaryPositions||[]).filter(Boolean))];}
function sideOf(slot){const id=String(slot?.id||'');if(/^(R|RAM|RCM|RDM|RWB|RB|RM|RW|RST)/.test(id))return'R';if(/^(L|LAM|LCM|LDM|LWB|LB|LM|LW|LST)/.test(id))return'L';return'C';}
function sets(slot){const side=sideOf(slot),f=slot?.family;if(f==='GK')return{natural:['GK'],cover:[]};if(f==='CB')return{natural:['DC','CB'],cover:side==='R'?['DR','RB','DMC','DM']:side==='L'?['DL','LB','DMC','DM']:['DMC','DM','DR','DL']};if(f==='FB')return side==='R'?{natural:['DR','RB'],cover:['WBR','RWB','MR','AMR']}:{natural:['DL','LB'],cover:['WBL','LWB','ML','AML']};if(f==='WB')return side==='R'?{natural:['WBR','RWB'],cover:['DR','RB','MR','AMR']}:{natural:['WBL','LWB'],cover:['DL','LB','ML','AML']};if(f==='DM')return{natural:['DMC','DM'],cover:['MC','CM','DC','CB']};if(f==='CM')return{natural:['MC','CM'],cover:['DMC','DM','AMC','AM']};if(f==='AM')return{natural:['AMC','AM'],cover:['MC','CM','ST','FC','CF']};if(f==='W')return side==='R'?{natural:['AMR','MR','RW','FR'],cover:['WBR','RWB','ST','FC','AMC']}:{natural:['AML','ML','LW','FL'],cover:['WBL','LWB','ST','FC','AMC']};if(f==='ST')return{natural:['ST','FC','CF','SC'],cover:['AMC','AMR','AML','AM']};return{natural:[],cover:[]};}
const matches=(code,allowed)=>allowed.includes(clean(code));
export function getPositionFit(p,slot){if(!p||!slot)return'unfamiliar';const s=sets(slot),primary=clean(p.primaryPosition),alts=alternativePositions(p).map(clean);if(matches(primary,s.natural))return'preferred';if(alts.some(c=>matches(c,s.natural)))return'secondary';if(matches(primary,s.cover)||alts.some(c=>matches(c,s.cover)))return'secondary';return'unfamiliar';}
const fitLabel=f=>f==='preferred'?'Preferred position':f==='secondary'?'Can cover this position':'Unsuitable position';
function keyPlayers(database,clubId){return new Set(database.players.filter(p=>p.clubId===clubId&&!p.isPlaceholder).sort((a,b)=>(b.currentAbility||0)-(a.currentAbility||0)||a.name.localeCompare(b.name)).slice(0,3).map(p=>p.id));}
function statusFor(c,p){const a=c.playerStatus?.[p.id]||{},b=p.status||{};return{condition:a.condition??b.condition??100,sharpness:a.sharpness??b.matchSharpness??88,morale:a.morale??b.morale??'Good',alert:(b.injuries&&b.injuries!=='None'?b.injuries:null)||(b.suspension&&b.suspension!=='None'?b.suspension:null)};}
function saveSelection(ids,database,c){if(ids.length!==11)return false;const players=ids.map(id=>playerById(database,id)).filter(Boolean);if(players.length!==11||!players.some(p=>p.positionGroup==='GK'))return false;c.lineupIds=ids;c.tacticalSetup=null;persist(c);return true;}

function injectStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.db-player-rating{display:none!important}.v044-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 13px;margin-bottom:10px;border:1px solid rgba(239,185,63,.16);border-radius:10px;background:rgba(255,255,255,.018)}.v044-toolbar button,.v044-actions button{min-height:36px;padding:0 12px;border:1px solid rgba(239,185,63,.28);border-radius:8px;background:#0c0b08;color:#d8bd72;font-size:8px;font-weight:950;letter-spacing:.08em;cursor:pointer}.v044-toolbar small{color:#7f786c;font-size:9px}.v044-legend{display:flex;gap:10px;flex-wrap:wrap;color:#8b8478;font-size:9px}.v044-legend i{display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:50%}.v044-legend .p{background:#4ec07c}.v044-legend .s{background:#d6953f}.v044-legend .u{background:#d65d55}
.v044-head,.v044-row{display:grid;grid-template-columns:30px 52px minmax(160px,1.2fr) 105px minmax(115px,1fr) 62px 62px 68px;gap:9px;align-items:center}.v044-head{padding:0 11px 6px;color:#716b61;font-size:8px;font-weight:900;letter-spacing:.1em}.v044-list{display:grid;gap:4px}.v044-row{min-height:56px;padding:7px 11px;border:1px solid rgba(239,185,63,.1);border-radius:8px;background:rgba(255,255,255,.014)}.v044-row.is-selected{border-color:rgba(239,185,63,.38);background:rgba(239,185,63,.05)}.v044-row input{width:17px;height:17px;accent-color:#e9b63d}.v044-pos{color:#e8cb73;font-size:10px;font-weight:950}.v044-name strong{display:flex;gap:5px;align-items:center;font-size:12px}.v044-name small,.v044-cell small{display:block;margin-top:3px;color:#716b61;font-size:8px}.v044-alt{color:#a49b8f;font-size:9px}.v044-cell b{font-size:10px}.v044-star{color:#f6d94a;text-shadow:0 0 8px rgba(246,217,74,.35)}.v044-profile{min-height:30px;border:1px solid rgba(239,185,63,.18);border-radius:7px;background:#0b0a07;color:#b9a572;font-size:8px;font-weight:900;cursor:pointer}
.v044-tactics{display:grid;grid-template-columns:minmax(400px,1.18fr) minmax(330px,.82fr);gap:18px}.v044-pitch{position:relative;min-height:640px;border:1px solid rgba(239,185,63,.32);border-radius:15px;background:repeating-linear-gradient(0deg,rgba(255,255,255,.018) 0 64px,rgba(255,255,255,.035) 65px 128px),linear-gradient(#17331f,#0c1d12);overflow:hidden}.v044-pitch:before{content:'';position:absolute;inset:5%;border:1px solid rgba(255,255,255,.3)}.v044-pitch:after{content:'';position:absolute;left:5%;right:5%;top:50%;border-top:1px solid rgba(255,255,255,.3)}.v044-player{position:absolute;z-index:2;transform:translate(-50%,-50%);width:124px;padding:7px;border:2px solid;border-radius:9px;background:rgba(7,8,6,.92);text-align:center}.v044-player.fit-preferred{border-color:#4ec07c}.v044-player.fit-secondary{border-color:#d6953f}.v044-player.fit-unfamiliar{border-color:#d65d55}.v044-player span{display:block;color:#e8cb73;font-size:8px;font-weight:950}.v044-player strong{display:block;margin-top:2px;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-player small{display:block;margin-top:2px;color:#8c8579;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-side{display:grid;align-content:start;gap:9px}.v044-card{padding:14px;border:1px solid rgba(239,185,63,.16);border-radius:11px;background:linear-gradient(145deg,rgba(22,20,14,.88),rgba(8,8,6,.94))}.v044-title{margin-bottom:9px;color:#e6bf52;font-size:9px;font-weight:950;letter-spacing:.11em}.v044-controls{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v044-control{display:grid;gap:4px}.v044-control span{color:#80786c;font-size:8px;font-weight:900}.v044-control select,.v044-role select{min-height:35px;border:1px solid rgba(255,255,255,.13);border-radius:7px;background:#0d0c09;color:#eee7da;padding:0 7px;font-size:9px}.v044-roles{display:grid;gap:4px;max-height:295px;overflow:auto}.v044-role{display:grid;grid-template-columns:38px minmax(85px,1fr) minmax(115px,1fr);gap:6px;align-items:center;padding:5px;border:1px solid rgba(255,255,255,.06);border-radius:7px}.v044-role>span{color:#e8cb73;font-size:8px;font-weight:950}.v044-role strong{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-actions{display:flex;gap:6px;flex-wrap:wrap}.v044-actions .primary{background:linear-gradient(#ffd363,#e5a72c);color:#171005;border-color:#f8ca5b}
@media(max-width:980px){.v044-head{display:none}.v044-row{grid-template-columns:28px 48px minmax(140px,1fr) 80px 60px}.v044-row>.v044-alt:nth-of-type(2),.v044-row>.v044-cell:nth-of-type(2),.v044-profile{display:none}.v044-tactics{grid-template-columns:1fr}.v044-pitch{min-height:550px}}@media(max-width:620px){.v044-toolbar{align-items:flex-start;flex-direction:column}.v044-row{grid-template-columns:25px 42px minmax(125px,1fr) 58px}.v044-row>.v044-alt,.v044-row>.v044-cell,.v044-profile{display:none}.v044-controls{grid-template-columns:1fr}.v044-player{width:90px}.v044-player small{display:none}}
`;s.textContent+=`
.career-app{background:#061326 url('./assets/homepage/squad-goal.webp') center/cover no-repeat;color:#eef3f6}.career-app:before{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(180deg,rgba(3,15,32,.88),rgba(3,15,32,.55) 34%,rgba(3,15,32,.84)),linear-gradient(90deg,rgba(3,15,32,.96),rgba(3,15,32,.38) 42%,rgba(3,15,32,.68))}.career-header,.career-layout{position:relative;z-index:1}.career-header{border-bottom-color:rgba(90,160,225,.34);background:rgba(4,19,39,.94)}.career-brand>span{border-color:#3b82c7;color:#8ee7a8;background:#0b315c}.career-brand em{color:#55dc7c}.career-club small,.career-round{color:#9caebe}.career-header-actions button,.career-secondary{border-color:#2b63a4;border-radius:0;background:#0a2242;color:#e9f1f6}.career-nav{border-right-color:rgba(47,104,169,.45);background:rgba(3,17,37,.84)}.career-nav-button{border-radius:0;border-color:transparent;color:#c2cfda}.career-nav-button:hover{background:rgba(21,64,111,.55)}.career-nav-button.is-active{border-color:#f4c342;color:#50dc78;background:rgba(21,77,55,.85)}.career-content{background:rgba(3,17,37,.2)}.career-page-heading{margin-bottom:18px}.career-page-heading h2{font-size:clamp(30px,3.6vw,48px);letter-spacing:.01em;text-transform:uppercase}.career-kpi-grid article,.career-panel{border-radius:0;border-color:rgba(47,104,169,.55);background:rgba(5,22,45,.87)}
.v044-squad-toolbar{display:grid;grid-template-columns:170px 170px 1fr;gap:8px;padding:10px;margin-bottom:10px;border:1px solid #24558e;border-radius:0;background:rgba(4,20,41,.94)}.v044-squad-toolbar label{display:grid;gap:4px;color:#c7d2dc;font-size:9px;font-weight:900;letter-spacing:.12em}.v044-squad-toolbar select{min-height:34px;border:1px solid #7890a4;border-radius:0;background:#6e7b87;color:#f2f5f7;padding:0 8px;font-size:12px;font-weight:800}.v044-squad-actions{display:flex;justify-content:flex-end;align-items:end;gap:6px}.v044-squad-actions button,.v044-squad-actions select{min-height:34px;padding:0 11px;border:1px solid #2d6dbb;border-radius:0;background:#0b2d62;color:#eef3f6;font-size:10px;font-weight:900;letter-spacing:.06em}.v044-squad-actions button:first-child{border-color:#f4c342;background:#164277;color:#f4c342}.v044-squad-actions button[data-v044-clear-squad]{background:#6e7b87;color:#fff;border-color:#c7d0d7}.v044-squad-actions select{background:#6e7b87;border-color:#c7d0d7}.v044-position-heading{display:flex;justify-content:space-between;align-items:center;padding:12px 14px 8px;background:rgba(4,20,41,.85)}.v044-position-heading strong{color:#f4c342;font-size:24px;letter-spacing:.02em}.v044-position-heading span{color:#9caebe;font-size:10px;font-weight:900;letter-spacing:.12em}.v044-position-filters{display:flex;gap:4px;flex-wrap:wrap;padding:0 14px 10px;background:rgba(4,20,41,.85)}.v044-position-filters button{min-width:48px;min-height:29px;padding:0 10px;border:1px solid #168447;border-radius:0;background:#08752e;color:#eef3f6;font-size:10px;font-weight:900;cursor:pointer}.v044-position-filters button.is-active{border-color:#f4c342;color:#f4c342;background:#174d36}.v044-squad-browser{border:1px solid #24558e;background:rgba(4,20,41,.82)}.v044-squad-browser>.v044-head{grid-template-columns:28px 52px minmax(180px,1fr) 105px 62px 62px 70px;padding:8px 12px;color:#9caebe;background:rgba(4,20,41,.9)}.v044-squad-browser .v044-list{grid-template-columns:repeat(2,minmax(0,1fr));gap:3px;padding:0 10px 10px}.v044-squad-browser .v044-row{grid-template-columns:28px 52px minmax(140px,1fr) 105px 62px 62px 70px;min-height:50px;padding:6px 10px;border:1px solid #17477c;border-radius:0;background:rgba(7,28,56,.9)}.v044-squad-browser .v044-row.is-selected{border-color:#55dc7c;background:rgba(23,77,55,.8)}.v044-squad-browser .v044-row input{accent-color:#55dc7c}.v044-squad-browser .v044-pos{color:#f4c342}.v044-squad-browser .v044-name strong{font-size:14px;color:#f1f5f7}.v044-squad-browser .v044-name small,.v044-squad-browser .v044-cell small{color:#9caebe}.v044-squad-browser .v044-status{color:#9caebe;font-size:9px;font-weight:800}.v044-squad-browser .v044-cell b{color:#f1f5f7;font-size:10px}.v044-squad-browser .v044-profile{min-height:28px;border-color:#2d6dbb;border-radius:0;background:#0a2242;color:#b9d7f0}.v044-squad-browser .v044-star{color:#f4c342}
@media(max-width:900px){.v044-squad-browser>.v044-head{display:none}.v044-squad-browser .v044-list{grid-template-columns:1fr}.v044-squad-browser .v044-row{grid-template-columns:28px 52px minmax(180px,1fr) 105px 62px 62px 70px}}@media(max-width:720px){.v044-squad-toolbar{grid-template-columns:1fr 1fr}.v044-squad-actions{grid-column:1/-1;justify-content:flex-start;flex-wrap:wrap}.v044-position-heading strong{font-size:19px}.v044-squad-browser .v044-row{grid-template-columns:26px 45px minmax(120px,1fr) 58px}.v044-squad-browser .v044-status,.v044-squad-browser .v044-cell,.v044-squad-browser .v044-profile{display:none}}
.career-app:has(.v044-squad-browser) .career-header{height:64px;grid-template-columns:220px 1fr auto;padding:0 18px}.career-app:has(.v044-squad-browser) .career-layout{height:calc(100vh - 64px)}.career-app:has(.v044-squad-browser) .career-content{overflow:hidden;padding:14px 22px 18px}.career-app:has(.v044-squad-browser) .career-page-heading{margin-bottom:8px}.career-app:has(.v044-squad-browser) .career-page-heading h2{font-size:30px}.career-app:has(.v044-squad-browser) .career-page-heading .eyebrow{margin-bottom:4px}.career-app:has(.v044-squad-browser) .lineup-counter{padding:6px 9px;border-color:#2f8c62;color:#8ee7a8}.career-app:has(.v044-squad-browser) .v044-squad-toolbar{gap:6px;padding:5px 8px;margin-bottom:6px}.career-app:has(.v044-squad-browser) .v044-squad-toolbar select{min-height:27px;padding:0 6px;font-size:10px}.career-app:has(.v044-squad-browser) .v044-squad-actions button,.career-app:has(.v044-squad-browser) .v044-squad-actions select{min-height:27px;padding:0 8px;font-size:9px}.career-app:has(.v044-squad-browser) .v044-position-heading{padding:5px 10px 4px}.career-app:has(.v044-squad-browser) .v044-position-heading strong{font-size:15px}.career-app:has(.v044-squad-browser) .v044-position-filters{gap:3px;padding:0 10px 5px}.career-app:has(.v044-squad-browser) .v044-position-filters button{min-width:38px;min-height:24px;padding:0 7px;font-size:9px}.career-app:has(.v044-squad-browser) .v044-squad-browser>.v044-head{grid-template-columns:22px 42px minmax(120px,1fr) 80px 45px 45px 56px;padding:4px 8px;font-size:7px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-list{gap:2px;padding:0 6px 6px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-row{grid-template-columns:22px 42px minmax(120px,1fr) 80px 45px 45px 56px;min-height:34px;padding:3px 6px;gap:5px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-row input{width:14px;height:14px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-name strong{font-size:11px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-name small{margin-top:1px;font-size:7px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-status{font-size:7px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-cell b{font-size:9px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-profile{min-height:23px;padding:0 5px;font-size:7px}.career-app:has(.v044-squad-browser) .v044-list .v044-profile{display:block}
@media(max-width:900px){.career-app:has(.v044-squad-browser) .career-header{height:72px}.career-app:has(.v044-squad-browser) .career-layout{height:calc(100vh - 72px)}.career-app:has(.v044-squad-browser) .career-content{overflow:auto;padding:24px 16px 50px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-list{grid-template-columns:1fr}}
@media(max-width:720px){.career-app:has(.v044-squad-browser) .career-header{height:72px}.career-app:has(.v044-squad-browser) .career-content{padding:18px 12px 40px}.career-app:has(.v044-squad-browser) .career-page-heading{align-items:flex-start;flex-direction:column;gap:6px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-row{grid-template-columns:26px 45px minmax(120px,1fr) 58px}.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-status,.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-cell,.career-app:has(.v044-squad-browser) .v044-squad-browser .v044-profile{display:none}}
.career-app{background:#061326;color:#eef3f6}.career-app:has(.career-nav-button[data-career-tab="squad"].is-active){background-image:url('./assets/homepage/squad-goal.webp');background-position:center;background-size:cover;background-repeat:no-repeat}
`;document.head.appendChild(s);}
function updateVersion(){const chip=document.querySelector('.version-chip');if(chip&&chip.textContent!==VERSION)chip.textContent=VERSION;const footer=document.querySelector('.footer-build');if(footer&&footer.textContent!=='V0.4.4 · SQUAD & TACTICS')footer.textContent='V0.4.4 · SQUAD & TACTICS';}

function renderSquad(root,c,database){
  if(root.dataset.v044Squad==='1')return;
  const oldList=root.querySelector('.career-squad-list'),oldActions=root.querySelector('.career-squad-actions');
  if(!oldList||!oldActions)return;
  root.dataset.v044Squad='1';
  const selected=new Set(c.lineupIds||[]),stars=keyPlayers(database,c.clubId),order={GK:0,DEF:1,MID:2,ATT:3};
  const squad=database.players.filter(p=>p.clubId===c.clubId&&!p.isPlaceholder).sort((a,b)=>order[a.positionGroup]-order[b.positionGroup]||displayName(a).localeCompare(displayName(b)));
  const positions=[...new Set(squad.map(p=>p.primaryPosition).filter(Boolean))];
  root.querySelector('.career-page-heading h2').textContent='Squad';
  root.querySelector('.career-page-heading .eyebrow').textContent='SQUAD · POSITION(S)';
  const round=root.querySelector('.career-round, .lineup-counter');
  if(round)round.textContent=`${squad.length} PLAYERS · FIRST TEAM`;
  oldActions.outerHTML=`<div class="v044-toolbar v044-squad-toolbar"><label>VIEW<select data-v044-view><option value="all">Squad</option><option value="first">First Team</option><option value="available">Available</option><option value="unavailable">Unavailable</option></select></label><label>SORT BY<select data-v044-sort><option value="position">Position</option><option value="name">Name</option><option value="condition">Condition</option><option value="sharpness">Sharpness</option><option value="ability">Ability</option></select></label><div class="v044-squad-actions"><button type="button" data-v044-auto-pick>AUTOPICK XI</button><button type="button" data-v044-clear-squad>CLEAR SQUAD</button><select data-v044-filter aria-label="Filter squad"><option value="all">FILTER · ALL</option><option value="GK">FILTER · GK</option><option value="DEF">FILTER · DEFENDERS</option><option value="MID">FILTER · MIDFIELDERS</option><option value="ATT">FILTER · ATTACKERS</option>${positions.map(p=>`<option value="${esc(p)}">FILTER · ${esc(p)}</option>`).join('')}</select></div></div>`;
  oldList.outerHTML=`<div class="v044-squad-browser"><div class="v044-position-heading"><strong>POSITION(S)</strong><span data-lineup-counter>${selected.size} / 11 SELECTED</span></div><div class="v044-position-filters"><button type="button" class="is-active" data-v044-position="all">ALL</button><button type="button" data-v044-position="GK">GK</button><button type="button" data-v044-position="DEF">DEF</button><button type="button" data-v044-position="MID">MID</button><button type="button" data-v044-position="ATT">ATT</button>${positions.map(p=>`<button type="button" data-v044-position="${esc(p)}">${esc(p)}</button>`).join('')}</div><div class="v044-head"><span>XI</span><span>POS</span><span>PLAYER</span><span>STATUS</span><span>CON</span><span>SHARP</span><span></span></div><div class="v044-list">${squad.map(p=>{const st=statusFor(c,p),name=displayName(p);return`<label class="v044-row ${selected.has(p.id)?'is-selected':''}" data-v044-row="${esc(p.id)}" data-position="${esc(p.primaryPosition||'')}" data-group="${esc(p.positionGroup||'')}" data-condition="${Math.round(st.condition)}" data-sharpness="${Math.round(st.sharpness)}" data-ability="${Number(p.currentAbility)||0}" data-status="${st.alert?'unavailable':'available'}"><input type="checkbox" value="${esc(p.id)}" ${selected.has(p.id)?'checked':''} data-v044-lineup aria-label="Select ${esc(name)}"><span class="v044-pos">${esc(p.primaryPosition||'—')}</span><span class="v044-name"><strong>${esc(name)}${stars.has(p.id)?'<i class="v044-star" title="Key player">★</i>':''}</strong><small>${esc(st.morale)}${st.alert?` · ${esc(st.alert)}`:''}</small></span><span class="v044-status">${st.alert?esc(st.alert):'AVAILABLE'}</span><span class="v044-cell"><b>${Math.round(st.condition)}%</b></span><span class="v044-cell"><b>${Math.round(st.sharpness)}%</b></span><button type="button" class="v044-profile" data-v044-profile="${esc(p.id)}">PROFILE</button></label>`;}).join('')}</div></div>`;
  const applyFilters=()=>{const group=root.querySelector('[data-v044-filter]')?.value||'all',view=root.querySelector('[data-v044-view]')?.value||'all',sort=root.querySelector('[data-v044-sort]')?.value||'position',rows=[...root.querySelectorAll('[data-v044-row]')];rows.sort((a,b)=>sort==='name'?a.querySelector('.v044-name strong').textContent.localeCompare(b.querySelector('.v044-name strong').textContent):sort==='condition'?Number(b.dataset.condition)-Number(a.dataset.condition):sort==='sharpness'?Number(b.dataset.sharpness)-Number(a.dataset.sharpness):sort==='ability'?Number(b.dataset.ability)-Number(a.dataset.ability):order[a.dataset.group]-order[b.dataset.group]||a.querySelector('.v044-name strong').textContent.localeCompare(b.querySelector('.v044-name strong').textContent));const list=root.querySelector('.v044-list');rows.forEach(row=>list.appendChild(row));rows.forEach(row=>{const matchesGroup=group==='all'||group===row.dataset.group||group===row.dataset.position;const matchesView=view==='all'||(view==='available'&&row.dataset.status==='available')||(view==='unavailable'&&row.dataset.status==='unavailable')||(view==='first'&&row.querySelector('input')?.checked);row.hidden=!(matchesGroup&&matchesView);});};
  root.querySelectorAll('[data-v044-position]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('[data-v044-position]').forEach(b=>b.classList.remove('is-active'));button.classList.add('is-active');const value=button.dataset.v044Position;root.querySelector('[data-v044-filter]').value=value;applyFilters();}));
  root.querySelectorAll('[data-v044-view],[data-v044-sort],[data-v044-filter]').forEach(control=>control.addEventListener('change',applyFilters));
  root.querySelector('[data-v044-auto-pick]')?.addEventListener('click',()=>{const byAbility=[...squad].sort((a,b)=>(b.currentAbility||0)-(a.currentAbility||0)),chosen=[];Object.entries({GK:1,DEF:4,MID:3,ATT:3}).forEach(([g,n])=>chosen.push(...byAbility.filter(p=>p.positionGroup===g).slice(0,n)));byAbility.forEach(p=>{if(chosen.length<11&&!chosen.some(x=>x.id===p.id))chosen.push(p);});c.lineupIds=chosen.slice(0,11).map(p=>p.id);c.tacticalSetup=null;persist(c);rerender('squad');});
  root.querySelector('[data-v044-clear-squad]')?.addEventListener('click',()=>{c.lineupIds=[];c.tacticalSetup=null;persist(c);rerender('squad');});
  root.querySelectorAll('[data-v044-lineup]').forEach(input=>input.addEventListener('change',()=>{let ids=[...root.querySelectorAll('[data-v044-lineup]:checked')].map(x=>x.value);if(ids.length>11){input.checked=false;ids=[...root.querySelectorAll('[data-v044-lineup]:checked')].map(x=>x.value);}root.querySelector(`[data-v044-row="${CSS.escape(input.value)}"]`)?.classList.toggle('is-selected',input.checked);const counter=root.querySelector('[data-lineup-counter]'),valid=ids.length===11&&ids.map(id=>playerById(database,id)).some(p=>p?.positionGroup==='GK');if(counter){counter.textContent=`${ids.length} / 11 SELECTED`;counter.classList.toggle('is-valid',valid);}if(valid)saveSelection(ids,database,c); }));
  root.querySelectorAll('[data-v044-profile]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();window.FLMPlayerProfile?.open(b.dataset.v044Profile);}));
  applyFilters();
}

function defaultTactics(c){return{formation:c.tactics?.formation||'4-3-3',mentality:c.tactics?.mentality||'Balanced',pressing:c.tactics?.pressing||'Standard',tempo:c.tactics?.tempo||'Standard',passing:c.tactics?.passing||'Mixed',width:c.tactics?.width||'Balanced',defensiveLine:c.tactics?.defensiveLine||'Standard'};}
function shapeFor(c,database,formation){return assignPlayersToFormation(c.lineupIds,formation,database,c.tacticalSetup?.formation===formation?c.tacticalSetup:null);}
function pitchHtml(shape,database){return shape.slots.map(slot=>{const a=shape.assignments.find(x=>x.slotId===slot.id),p=playerById(database,a?.playerId),fit=getPositionFit(p,slot),star=p&&keyPlayers(database,p.clubId).has(p.id)?'<i class="v044-star">★</i>':'';return`<div class="v044-player fit-${fit}" style="left:${slot.x}%;top:${slot.y}%" title="${esc(fitLabel(fit))}"><span>${esc(slot.label)}</span><strong>${esc(p?displayName(p):'—')} ${star}</strong><small>${esc(a?.role||'')} · ${esc(fitLabel(fit))}</small></div>`;}).join('');}
function rolesHtml(shape,database){return shape.slots.map(slot=>{const a=shape.assignments.find(x=>x.slotId===slot.id),p=playerById(database,a?.playerId);return`<div class="v044-role"><span>${esc(slot.label)}</span><strong>${esc(p?displayName(p):'—')}</strong><select data-v044-role="${esc(slot.id)}">${slot.roles.map(r=>`<option ${a?.role===r?'selected':''}>${esc(r)}</option>`).join('')}</select></div>`;}).join('');}
function field(label,key,values,value){return`<label class="v044-control"><span>${esc(label)}</span><select data-v044-tactic="${esc(key)}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function renderTactics(root,c,database){if(root.dataset.v044Tactics==='1')return;const old=root.querySelector('.career-tactics-grid');if(!old)return;root.dataset.v044Tactics='1';const t=defaultTactics(c);let shape=shapeFor(c,database,t.formation);root.querySelector('.career-page-heading h2').textContent='Tactics Centre';root.querySelector('.career-round').textContent='PRE-MATCH · ROLES · POSITION FIT';old.outerHTML=`<div class="v044-tactics"><div><div class="v044-pitch" data-v044-pitch>${pitchHtml(shape,database)}</div><div class="v044-legend" style="margin-top:9px"><span><i class="p"></i>Preferred</span><span><i class="s"></i>Can cover</span><span><i class="u"></i>Wrong position</span></div></div><aside class="v044-side"><section class="v044-card"><div class="v044-title">TEAM INSTRUCTIONS</div><div class="v044-controls">${field('FORMATION','formation',Object.keys(FORMATION_LAYOUTS),t.formation)}${field('MENTALITY','mentality',TACTIC_OPTIONS.mentality,t.mentality)}${field('PRESSING','pressing',TACTIC_OPTIONS.pressing,t.pressing)}${field('TEMPO','tempo',TACTIC_OPTIONS.tempo,t.tempo)}${field('PASSING','passing',TACTIC_OPTIONS.passing,t.passing)}${field('WIDTH','width',TACTIC_OPTIONS.width,t.width)}${field('DEFENSIVE LINE','defensiveLine',TACTIC_OPTIONS.defensiveLine,t.defensiveLine)}</div></section><section class="v044-card"><div class="v044-title">PLAYER ROLES</div><div class="v044-roles" data-v044-roles>${rolesHtml(shape,database)}</div></section><section class="v044-card"><div class="v044-title">TACTIC SLOTS</div><div class="v044-actions"><button data-v044-load="1">LOAD 1</button><button data-v044-save="1">SAVE 1</button><button data-v044-load="2">LOAD 2</button><button data-v044-save="2">SAVE 2</button><button data-v044-load="3">LOAD 3</button><button data-v044-save="3">SAVE 3</button></div></section><div class="v044-actions"><button class="primary" data-v044-apply>SAVE MATCH PLAN</button></div></aside></div>`;
const refresh=f=>{shape=shapeFor(c,database,f);root.querySelector('[data-v044-pitch]').innerHTML=pitchHtml(shape,database);root.querySelector('[data-v044-roles]').innerHTML=rolesHtml(shape,database);};root.querySelector('[data-v044-tactic="formation"]')?.addEventListener('change',e=>refresh(e.target.value));
const collect=()=>Object.fromEntries([...root.querySelectorAll('[data-v044-tactic]')].map(x=>[x.dataset.v044Tactic,x.value]));const withRoles=values=>{const next=assignPlayersToFormation(c.lineupIds,values.formation,database,shape?.formation===values.formation?shape:null);next.assignments.forEach(a=>{const f=root.querySelector(`[data-v044-role="${CSS.escape(a.slotId)}"]`),slot=next.slots.find(s=>s.id===a.slotId);if(f&&slot?.roles.includes(f.value))a.role=f.value;});return next;};
root.querySelector('[data-v044-apply]')?.addEventListener('click',()=>{const values=collect();c.tactics={...c.tactics,...values};c.tacticalSetup=withRoles(values);persist(c);rerender('tactics');});root.querySelectorAll('[data-v044-save]').forEach(b=>b.addEventListener('click',()=>{const values=collect();c.tacticPresets||={};c.tacticPresets[b.dataset.v044Save]={tactics:values,tacticalSetup:withRoles(values)};persist(c);b.textContent=`SAVED ${b.dataset.v044Save}`;}));root.querySelectorAll('[data-v044-load]').forEach(b=>b.addEventListener('click',()=>{const p=c.tacticPresets?.[b.dataset.v044Load];if(!p){b.textContent=`EMPTY ${b.dataset.v044Load}`;return;}c.tactics={...c.tactics,...p.tactics};c.tacticalSetup=p.tacticalSetup;persist(c);rerender('tactics');}));}

async function enhance(){const c=career(),root=document.querySelector('.career-content');if(!manager()||!c||!root)return;const database=await db();if(root.querySelector('.career-squad-list'))renderSquad(root,c,database);if(root.querySelector('.career-tactics-grid'))renderTactics(root,c,database);}
function queue(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(async()=>{renderQueued=false;try{await enhance();}catch(e){console.error('V0.4.4 enhancement failed',e);}});}
function boot(){injectStyles();updateVersion();new MutationObserver(()=>{updateVersion();queue();}).observe(document.body,{childList:true,subtree:true});queue();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.FLMPositionFit={getPositionFit,preferredPositions,alternativePositions};
