import { FORMATION_LAYOUTS, TACTIC_OPTIONS, assignPlayersToFormation } from './matchday-engine-v0431.js?v=0.4.3.1';

const SAVE_KEY='flm-career-save', STYLE_ID='flm-v044-career-style', VERSION='V0.4.4';
let cachedDb=null, renderQueued=false;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const clean=v=>String(v||'').toUpperCase().replaceAll(' ','');
const manager=()=>window.FLMManager;
const career=()=>manager()?.activeCareer||null;
const db=async()=>cachedDb||=(await manager().loadDatabase());
const playerById=(database,id)=>database.players.find(p=>p.id===id);

function persist(c){c.updatedAt=new Date().toISOString();localStorage.setItem(SAVE_KEY,JSON.stringify(c));const s=document.querySelector('[data-career-save-status]');if(s)s.textContent='SAVED';}
function rerender(tab){requestAnimationFrame(()=>document.querySelector(`[data-career-tab="${tab}"]`)?.click());}
function preferredPositions(p){return [p?.primaryPosition].filter(Boolean);}
function alternativePositions(p){return [...new Set((p?.secondaryPositions||[]).filter(Boolean))];}
function sideOf(slot){const id=String(slot?.id||'');if(/^(R|RAM|RCM|RDM|RWB|RB|RM|RW|RST)/.test(id))return'R';if(/^(L|LAM|LCM|LDM|LWB|LB|LM|LW|LST)/.test(id))return'L';return'C';}
function sets(slot){const side=sideOf(slot),f=slot?.family;if(f==='GK')return{natural:['GK'],cover:[]};if(f==='CB')return{natural:['DC','CB'],cover:side==='R'?['DR','RB','DMC','DM']:side==='L'?['DL','LB','DMC','DM']:['DMC','DM','DR','DL']};if(f==='FB')return side==='R'?{natural:['DR','RB'],cover:['WBR','RWB','MR','AMR']}:{natural:['DL','LB'],cover:['WBL','LWB','ML','AML']};if(f==='WB')return side==='R'?{natural:['WBR','RWB'],cover:['DR','RB','MR','AMR']}:{natural:['WBL','LWB'],cover:['DL','LB','ML','AML']};if(f==='DM')return{natural:['DMC','DM'],cover:['MC','CM','DC','CB']};if(f==='CM')return{natural:['MC','CM'],cover:['DMC','DM','AMC','AM']};if(f==='AM')return{natural:['AMC','AM'],cover:['MC','CM','ST','FC','CF']};if(f==='W')return side==='R'?{natural:['AMR','MR','RW','FR'],cover:['WBR','RWB','ST','FC','AMC']}:{natural:['AML','ML','LW','FL'],cover:['WBL','LWB','ST','FC','AMC']};if(f==='ST')return{natural:['ST','FC','CF','SC'],cover:['AMC','AMR','AML','AM']};return{natural:[],cover:[]};}
const matches=(code,allowed)=>allowed.includes(clean(code));
export function getPositionFit(p,slot){if(!p||!slot)return'unfamiliar';const s=sets(slot),primary=clean(p.primaryPosition),alts=alternativePositions(p).map(clean);if(matches(primary,s.natural))return'preferred';if(alts.some(c=>matches(c,s.natural)))return'secondary';if(matches(primary,s.cover)||alts.some(c=>matches(c,s.cover)))return'secondary';return'unfamiliar';}
const fitLabel=f=>f==='preferred'?'Preferred position':f==='secondary'?'Can cover this position':'Unsuitable position';
function keyPlayers(database,clubId){return new Set(database.players.filter(p=>p.clubId===clubId&&!p.isPlaceholder).sort((a,b)=>(b.currentAbility||0)-(a.currentAbility||0)||a.name.localeCompare(b.name)).slice(0,3).map(p=>p.id));}
function statusFor(c,p){const a=c.playerStatus?.[p.id]||{},b=p.status||{};return{condition:a.condition??b.condition??100,sharpness:a.sharpness??b.matchSharpness??88,morale:a.morale??b.morale??'Good',alert:(b.injuries&&b.injuries!=='None'?b.injuries:null)||(b.suspension&&b.suspension!=='None'?b.suspension:null)};}
function saveSelection(ids,database,c){if(ids.length!==11)return false;const players=ids.map(id=>playerById(database,id)).filter(Boolean);if(players.length!==11||!players.some(p=>p.positionGroup==='GK'))return false;c.lineupIds=ids;c.tacticalSetup=null;persist(c);return true;}

function injectStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.db-player-rating{display:none!important}.v044-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 13px;margin-bottom:10px;border:1px solid rgba(239,185,63,.16);border-radius:10px;background:rgba(255,255,255,.018)}.v044-toolbar button,.v044-actions button{min-height:36px;padding:0 12px;border:1px solid rgba(239,185,63,.28);border-radius:8px;background:#0c0b08;color:#d8bd72;font-size:8px;font-weight:950;letter-spacing:.08em;cursor:pointer}.v044-toolbar small{color:#7f786c;font-size:9px}.v044-legend{display:flex;gap:10px;flex-wrap:wrap;color:#8b8478;font-size:9px}.v044-legend i{display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:50%}.v044-legend .p{background:#4ec07c}.v044-legend .s{background:#d6953f}.v044-legend .u{background:#d65d55}
.v044-head,.v044-row{display:grid;grid-template-columns:30px 52px minmax(160px,1.2fr) 105px minmax(115px,1fr) 62px 62px 68px;gap:9px;align-items:center}.v044-head{padding:0 11px 6px;color:#716b61;font-size:8px;font-weight:900;letter-spacing:.1em}.v044-list{display:grid;gap:4px}.v044-row{min-height:56px;padding:7px 11px;border:1px solid rgba(239,185,63,.1);border-radius:8px;background:rgba(255,255,255,.014)}.v044-row.is-selected{border-color:rgba(239,185,63,.38);background:rgba(239,185,63,.05)}.v044-row input{width:17px;height:17px;accent-color:#e9b63d}.v044-pos{color:#e8cb73;font-size:10px;font-weight:950}.v044-name strong{display:flex;gap:5px;align-items:center;font-size:12px}.v044-name small,.v044-cell small{display:block;margin-top:3px;color:#716b61;font-size:8px}.v044-alt{color:#a49b8f;font-size:9px}.v044-cell b{font-size:10px}.v044-star{color:#f6d94a;text-shadow:0 0 8px rgba(246,217,74,.35)}.v044-profile{min-height:30px;border:1px solid rgba(239,185,63,.18);border-radius:7px;background:#0b0a07;color:#b9a572;font-size:8px;font-weight:900;cursor:pointer}
.v044-tactics{display:grid;grid-template-columns:minmax(400px,1.18fr) minmax(330px,.82fr);gap:18px}.v044-pitch{position:relative;min-height:640px;border:1px solid rgba(239,185,63,.32);border-radius:15px;background:repeating-linear-gradient(0deg,rgba(255,255,255,.018) 0 64px,rgba(255,255,255,.035) 65px 128px),linear-gradient(#17331f,#0c1d12);overflow:hidden}.v044-pitch:before{content:'';position:absolute;inset:5%;border:1px solid rgba(255,255,255,.3)}.v044-pitch:after{content:'';position:absolute;left:5%;right:5%;top:50%;border-top:1px solid rgba(255,255,255,.3)}.v044-player{position:absolute;z-index:2;transform:translate(-50%,-50%);width:124px;padding:7px;border:2px solid;border-radius:9px;background:rgba(7,8,6,.92);text-align:center}.v044-player.fit-preferred{border-color:#4ec07c}.v044-player.fit-secondary{border-color:#d6953f}.v044-player.fit-unfamiliar{border-color:#d65d55}.v044-player span{display:block;color:#e8cb73;font-size:8px;font-weight:950}.v044-player strong{display:block;margin-top:2px;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-player small{display:block;margin-top:2px;color:#8c8579;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-side{display:grid;align-content:start;gap:9px}.v044-card{padding:14px;border:1px solid rgba(239,185,63,.16);border-radius:11px;background:linear-gradient(145deg,rgba(22,20,14,.88),rgba(8,8,6,.94))}.v044-title{margin-bottom:9px;color:#e6bf52;font-size:9px;font-weight:950;letter-spacing:.11em}.v044-controls{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v044-control{display:grid;gap:4px}.v044-control span{color:#80786c;font-size:8px;font-weight:900}.v044-control select,.v044-role select{min-height:35px;border:1px solid rgba(255,255,255,.13);border-radius:7px;background:#0d0c09;color:#eee7da;padding:0 7px;font-size:9px}.v044-roles{display:grid;gap:4px;max-height:295px;overflow:auto}.v044-role{display:grid;grid-template-columns:38px minmax(85px,1fr) minmax(115px,1fr);gap:6px;align-items:center;padding:5px;border:1px solid rgba(255,255,255,.06);border-radius:7px}.v044-role>span{color:#e8cb73;font-size:8px;font-weight:950}.v044-role strong{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v044-actions{display:flex;gap:6px;flex-wrap:wrap}.v044-actions .primary{background:linear-gradient(#ffd363,#e5a72c);color:#171005;border-color:#f8ca5b}
@media(max-width:980px){.v044-head{display:none}.v044-row{grid-template-columns:28px 48px minmax(140px,1fr) 80px 60px}.v044-row>.v044-alt:nth-of-type(2),.v044-row>.v044-cell:nth-of-type(2),.v044-profile{display:none}.v044-tactics{grid-template-columns:1fr}.v044-pitch{min-height:550px}}@media(max-width:620px){.v044-toolbar{align-items:flex-start;flex-direction:column}.v044-row{grid-template-columns:25px 42px minmax(125px,1fr) 58px}.v044-row>.v044-alt,.v044-row>.v044-cell,.v044-profile{display:none}.v044-controls{grid-template-columns:1fr}.v044-player{width:90px}.v044-player small{display:none}}
`;document.head.appendChild(s);}
function updateVersion(){const chip=document.querySelector('.version-chip');if(chip&&chip.textContent!==VERSION)chip.textContent=VERSION;const footer=document.querySelector('.footer-build');if(footer&&footer.textContent!=='V0.4.4 · SQUAD & TACTICS')footer.textContent='V0.4.4 · SQUAD & TACTICS';}

function renderSquad(root,c,database){if(root.dataset.v044Squad==='1')return;const oldList=root.querySelector('.career-squad-list'),oldActions=root.querySelector('.career-squad-actions');if(!oldList||!oldActions)return;root.dataset.v044Squad='1';const selected=new Set(c.lineupIds||[]),stars=keyPlayers(database,c.clubId),order={GK:0,DEF:1,MID:2,ATT:3},squad=database.players.filter(p=>p.clubId===c.clubId&&!p.isPlaceholder).sort((a,b)=>order[a.positionGroup]-order[b.positionGroup]||a.name.localeCompare(b.name));root.querySelector('.career-page-heading h2').textContent='Squad';root.querySelector('.career-page-heading .eyebrow').textContent='SQUAD · POSITION(S)';oldActions.outerHTML=`<div class="v044-toolbar"><div><button data-v044-auto-pick>AUTO PICK XI</button> <small>★ key player · overall ability hidden</small></div><div class="v044-legend"><span><i class="p"></i>Preferred</span><span><i class="s"></i>Cover</span><span><i class="u"></i>Wrong position</span></div></div>`;oldList.outerHTML=`<div><div class="v044-head"><span>XI</span><span>POS</span><span>PLAYER</span><span>PREFERRED</span><span>ALTERNATIVES</span><span>CON</span><span>SHARP</span><span></span></div><div class="v044-list">${squad.map(p=>{const st=statusFor(c,p),alts=alternativePositions(p);return`<label class="v044-row ${selected.has(p.id)?'is-selected':''}" data-v044-row="${esc(p.id)}"><input type="checkbox" value="${esc(p.id)}" ${selected.has(p.id)?'checked':''} data-v044-lineup><span class="v044-pos">${esc(p.primaryPosition||'—')}</span><span class="v044-name"><strong>${esc(p.name)}${stars.has(p.id)?'<i class="v044-star" title="Key player">★</i>':''}</strong><small>${esc(st.morale)}${st.alert?` · ${esc(st.alert)}`:''}</small></span><span class="v044-alt">${esc(preferredPositions(p).join(', ')||'—')}</span><span class="v044-alt">${esc(alts.join(', ')||'—')}</span><span class="v044-cell"><small>CON</small><b>${Math.round(st.condition)}%</b></span><span class="v044-cell"><small>SHARP</small><b>${Math.round(st.sharpness)}%</b></span><button type="button" class="v044-profile" data-v044-profile="${esc(p.id)}">PROFILE</button></label>`;}).join('')}</div></div>`;
root.querySelector('[data-v044-auto-pick]')?.addEventListener('click',()=>{const byAbility=[...squad].sort((a,b)=>(b.currentAbility||0)-(a.currentAbility||0)),chosen=[];Object.entries({GK:1,DEF:4,MID:3,ATT:3}).forEach(([g,n])=>chosen.push(...byAbility.filter(p=>p.positionGroup===g).slice(0,n)));byAbility.forEach(p=>{if(chosen.length<11&&!chosen.some(x=>x.id===p.id))chosen.push(p);});c.lineupIds=chosen.slice(0,11).map(p=>p.id);c.tacticalSetup=null;persist(c);rerender('squad');});
root.querySelectorAll('[data-v044-lineup]').forEach(input=>input.addEventListener('change',()=>{let ids=[...root.querySelectorAll('[data-v044-lineup]:checked')].map(x=>x.value);if(ids.length>11){input.checked=false;ids=[...root.querySelectorAll('[data-v044-lineup]:checked')].map(x=>x.value);}root.querySelector(`[data-v044-row="${CSS.escape(input.value)}"]`)?.classList.toggle('is-selected',input.checked);const counter=root.querySelector('[data-lineup-counter]'),valid=ids.length===11&&ids.map(id=>playerById(database,id)).some(p=>p?.positionGroup==='GK');if(counter){counter.textContent=`${ids.length} / 11 SELECTED`;counter.classList.toggle('is-valid',valid);}if(valid)saveSelection(ids,database,c);}));
root.querySelectorAll('[data-v044-profile]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();window.FLMPlayerProfile?.open(b.dataset.v044Profile);}));}

function defaultTactics(c){return{formation:c.tactics?.formation||'4-3-3',mentality:c.tactics?.mentality||'Balanced',pressing:c.tactics?.pressing||'Standard',tempo:c.tactics?.tempo||'Standard',passing:c.tactics?.passing||'Mixed',width:c.tactics?.width||'Balanced',defensiveLine:c.tactics?.defensiveLine||'Standard'};}
function shapeFor(c,database,formation){return assignPlayersToFormation(c.lineupIds,formation,database,c.tacticalSetup?.formation===formation?c.tacticalSetup:null);}
function pitchHtml(shape,database){return shape.slots.map(slot=>{const a=shape.assignments.find(x=>x.slotId===slot.id),p=playerById(database,a?.playerId),fit=getPositionFit(p,slot),star=p&&keyPlayers(database,p.clubId).has(p.id)?'<i class="v044-star">★</i>':'';return`<div class="v044-player fit-${fit}" style="left:${slot.x}%;top:${slot.y}%" title="${esc(fitLabel(fit))}"><span>${esc(slot.label)}</span><strong>${esc(p?.name||'—')} ${star}</strong><small>${esc(a?.role||'')} · ${esc(fitLabel(fit))}</small></div>`;}).join('');}
function rolesHtml(shape,database){return shape.slots.map(slot=>{const a=shape.assignments.find(x=>x.slotId===slot.id),p=playerById(database,a?.playerId);return`<div class="v044-role"><span>${esc(slot.label)}</span><strong>${esc(p?.name||'—')}</strong><select data-v044-role="${esc(slot.id)}">${slot.roles.map(r=>`<option ${a?.role===r?'selected':''}>${esc(r)}</option>`).join('')}</select></div>`;}).join('');}
function field(label,key,values,value){return`<label class="v044-control"><span>${esc(label)}</span><select data-v044-tactic="${esc(key)}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function renderTactics(root,c,database){if(root.dataset.v044Tactics==='1')return;const old=root.querySelector('.career-tactics-grid');if(!old)return;root.dataset.v044Tactics='1';const t=defaultTactics(c);let shape=shapeFor(c,database,t.formation);root.querySelector('.career-page-heading h2').textContent='Tactics Centre';root.querySelector('.career-round').textContent='PRE-MATCH · ROLES · POSITION FIT';old.outerHTML=`<div class="v044-tactics"><div><div class="v044-pitch" data-v044-pitch>${pitchHtml(shape,database)}</div><div class="v044-legend" style="margin-top:9px"><span><i class="p"></i>Preferred</span><span><i class="s"></i>Can cover</span><span><i class="u"></i>Wrong position</span></div></div><aside class="v044-side"><section class="v044-card"><div class="v044-title">TEAM INSTRUCTIONS</div><div class="v044-controls">${field('FORMATION','formation',Object.keys(FORMATION_LAYOUTS),t.formation)}${field('MENTALITY','mentality',TACTIC_OPTIONS.mentality,t.mentality)}${field('PRESSING','pressing',TACTIC_OPTIONS.pressing,t.pressing)}${field('TEMPO','tempo',TACTIC_OPTIONS.tempo,t.tempo)}${field('PASSING','passing',TACTIC_OPTIONS.passing,t.passing)}${field('WIDTH','width',TACTIC_OPTIONS.width,t.width)}${field('DEFENSIVE LINE','defensiveLine',TACTIC_OPTIONS.defensiveLine,t.defensiveLine)}</div></section><section class="v044-card"><div class="v044-title">PLAYER ROLES</div><div class="v044-roles" data-v044-roles>${rolesHtml(shape,database)}</div></section><section class="v044-card"><div class="v044-title">TACTIC SLOTS</div><div class="v044-actions"><button data-v044-load="1">LOAD 1</button><button data-v044-save="1">SAVE 1</button><button data-v044-load="2">LOAD 2</button><button data-v044-save="2">SAVE 2</button><button data-v044-load="3">LOAD 3</button><button data-v044-save="3">SAVE 3</button></div></section><div class="v044-actions"><button class="primary" data-v044-apply>SAVE MATCH PLAN</button></div></aside></div>`;
const refresh=f=>{shape=shapeFor(c,database,f);root.querySelector('[data-v044-pitch]').innerHTML=pitchHtml(shape,database);root.querySelector('[data-v044-roles]').innerHTML=rolesHtml(shape,database);};root.querySelector('[data-v044-tactic="formation"]')?.addEventListener('change',e=>refresh(e.target.value));
const collect=()=>Object.fromEntries([...root.querySelectorAll('[data-v044-tactic]')].map(x=>[x.dataset.v044Tactic,x.value]));const withRoles=values=>{const next=assignPlayersToFormation(c.lineupIds,values.formation,database,shape?.formation===values.formation?shape:null);next.assignments.forEach(a=>{const f=root.querySelector(`[data-v044-role="${CSS.escape(a.slotId)}"]`),slot=next.slots.find(s=>s.id===a.slotId);if(f&&slot?.roles.includes(f.value))a.role=f.value;});return next;};
root.querySelector('[data-v044-apply]')?.addEventListener('click',()=>{const values=collect();c.tactics={...c.tactics,...values};c.tacticalSetup=withRoles(values);persist(c);rerender('tactics');});root.querySelectorAll('[data-v044-save]').forEach(b=>b.addEventListener('click',()=>{const values=collect();c.tacticPresets||={};c.tacticPresets[b.dataset.v044Save]={tactics:values,tacticalSetup:withRoles(values)};persist(c);b.textContent=`SAVED ${b.dataset.v044Save}`;}));root.querySelectorAll('[data-v044-load]').forEach(b=>b.addEventListener('click',()=>{const p=c.tacticPresets?.[b.dataset.v044Load];if(!p){b.textContent=`EMPTY ${b.dataset.v044Load}`;return;}c.tactics={...c.tactics,...p.tactics};c.tacticalSetup=p.tacticalSetup;persist(c);rerender('tactics');}));}

async function enhance(){const c=career(),root=document.querySelector('.career-content');if(!manager()||!c||!root)return;const database=await db();if(root.querySelector('.career-squad-list'))renderSquad(root,c,database);if(root.querySelector('.career-tactics-grid'))renderTactics(root,c,database);}
function queue(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(async()=>{renderQueued=false;try{await enhance();}catch(e){console.error('V0.4.4 enhancement failed',e);}});}
function boot(){injectStyles();updateVersion();new MutationObserver(()=>{updateVersion();queue();}).observe(document.body,{childList:true,subtree:true});queue();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.FLMPositionFit={getPositionFit,preferredPositions,alternativePositions};
