import test from 'node:test';
import assert from 'node:assert/strict';
import { STEP_FOUR_DIVISION_IDS } from '../national-league-step-four-world-v1.js';
import {
  STEP_FIVE_DIVISION_IDS,
  STEP_FIVE_2026_27_MEMBERSHIPS,
  STEP_FIVE_2026_27_TOTAL_CLUBS,
  simulateStepFiveDivisionSeason
} from '../national-league-step-five-world-v1.js';
import { finaliseSeason } from '../season-finalisation-v8.js';
import { rolloverPremierLeagueSeason, validatePremierLeagueRollover } from '../premier-league-rollover-v3.js';

const clubIds=()=>Array.from({length:20},(_,i)=>`v8-pl-${String(i+1).padStart(2,'0')}`);
function fixtures(ids){const matches=[];let serial=0;for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++){matches.push({id:`v8-${++serial}-a`,played:true,homeClubId:ids[a],awayClubId:ids[b],homeGoals:1,awayGoals:0});matches.push({id:`v8-${++serial}-b`,played:true,homeClubId:ids[b],awayClubId:ids[a],homeGoals:0,awayGoals:1});}return[matches];}
function table(ids,protectedId){const ordered=[protectedId,...ids.filter(id=>id!==protectedId)];return ordered.map((clubId,index)=>({clubId,played:38,won:Math.max(1,29-index),drawn:3,lost:6+index,goalsFor:90-index,goalsAgainst:30+index,goalDifference:60-index*2,points:100-index*4}));}
function dbFixture(){const ids=clubIds(),clubs=ids.map((id,index)=>({id,name:`V8 Premier Club ${index+1}`,shortName:`V8 ${index+1}`,providerName:`V8 Premier Club ${index+1}`,countryCode:'ENG',leagueId:'eng-premier-league',venue:`Ground ${index+1}`,reputation:7100-index*20,isPlaceholder:false})),shape=[['GK','GK'],['DEF','DR'],['DEF','DC'],['DEF','DC'],['DEF','DL'],['MID','DMC'],['MID','MC'],['MID','AMC'],['ATT','AMR'],['ATT','ST'],['ATT','AML']],players=clubs.flatMap((club,ci)=>shape.map(([positionGroup,primaryPosition],pi)=>({id:`${club.id}-p${pi+1}`,name:`${club.name} Player ${pi+1}`,clubId:club.id,positionGroup,primaryPosition,currentAbility:137+(20-ci)+(pi%3),potentialAbility:165,isPlaceholder:false})));return{clubs,players};}
function careerFixture(){const ids=clubIds();return{version:2,id:'pyramid-v8-career',seed:'pyramid-v8-seed',managerName:'V8 Manager',clubId:ids[0],leagueId:'eng-premier-league',competitionId:'eng-premier-league',competitionName:'Premier League',season:'2026/27',status:'complete',roundIndex:38,fixtures:fixtures(ids),table:table(ids,ids[0]),seasonClubs:ids.map((id,index)=>({id,name:`V8 Premier Club ${index+1}`,strength:82-index*.4})),seasonClubIds:ids,seasonHistory:[],worldHistory:[],lowerLeagueHistory:[],worldMemberships:[],worldBoundaries:[],seasonEndDate:'2027-05-30',currentDate:'2027-05-30',lastMatch:{date:'2027-05-30'},calendar:{currentDate:'2027-05-30',fixturesReleased:true},preseason:{phase:'complete'},worldClock:{schemaVersion:2,season:'2026/27',acknowledgedMilestones:[],history:[],totalDaysAdvanced:300},tactics:{formation:'4-3-3',mentality:'Balanced',pressing:'Standard'},lineupIds:Array.from({length:11},(_,index)=>`${ids[0]}-p${index+1}`),playerStatus:{}};}
function completeActiveSeason(career){const ids=[...career.seasonClubIds];career.table=table(ids,career.clubId);career.fixtures=career.fixtures.map(round=>round.map(match=>({...match,played:true,homeGoals:1,awayGoals:0})));career.status='complete';career.roundIndex=38;career.currentDate=career.seasonEndDate;career.calendar.currentDate=career.seasonEndDate;career.lastMatch={date:career.seasonEndDate};const result=finaliseSeason(career,{completedAt:`${career.seasonEndDate}T18:00:00.000Z`});assert.equal(result.status,'finalised');return result;}

test('FA 2026/27 Step 5 constitution contains 16 divisions and 320 unique clubs',()=>{assert.equal(STEP_FIVE_DIVISION_IDS.length,16);assert.equal(STEP_FIVE_2026_27_TOTAL_CLUBS,320);const all=STEP_FIVE_DIVISION_IDS.flatMap(id=>STEP_FIVE_2026_27_MEMBERSHIPS[id].map(c=>c.id));assert.equal(all.length,320);assert.equal(new Set(all).size,320);const sizes=STEP_FIVE_DIVISION_IDS.map(id=>STEP_FIVE_2026_27_MEMBERSHIPS[id].length);assert.equal(sizes.filter(n=>n===18).length,2);assert.equal(sizes.filter(n=>n===20).length,12);assert.equal(sizes.filter(n=>n===22).length,2);});

test('all Step 5 divisions use their real size and produce 32 promoted and 32 relegated clubs',()=>{let matches=0,promoted=0,relegated=0;for(const id of STEP_FIVE_DIVISION_IDS){const clubs=STEP_FIVE_2026_27_MEMBERSHIPS[id],outcome=simulateStepFiveDivisionSeason({competitionId:id,season:'2026/27',clubs,seed:'v8-step5-test'});assert.equal(outcome.status,'complete');assert.equal(outcome.clubCount,clubs.length);assert.equal(outcome.regularSeasonMatches,clubs.length*(clubs.length-1));assert.equal(outcome.regularSeasonMatchesPerClub,(clubs.length-1)*2);assert.equal(outcome.promotedClubIds.length,2);assert.equal(outcome.relegatedClubIds.length,2);assert.equal(outcome.playoffClubIds.length,4);matches+=outcome.regularSeasonMatches;promoted+=2;relegated+=2;}assert.equal(matches,6096);assert.equal(promoted,32);assert.equal(relegated,32);});

test('Step 5 completes 2027/28 Step 4 and moves the honest boundary to Step 6',()=>{const career=careerFixture(),result=finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});assert.equal(Object.keys(result.stepFiveDivisions).length,16);for(const division of Object.values(result.stepFiveDivisions))assert.equal(division.status,'finalised');const aggregate=career.worldMemberships.find(r=>r.key==='eng-national-league-step-four:2027/28');assert.equal(aggregate.status,'complete');assert.equal(aggregate.clubCount,176);assert.equal(aggregate.promotedFromStepFiveClubIds.length,32);assert.equal(aggregate.relegatedFromStepThreeClubIds.length,16);assert.equal(new Set(aggregate.clubs.map(c=>c.id)).size,176);for(const id of STEP_FOUR_DIVISION_IDS){const membership=career.worldMemberships.find(r=>r.key===`${id}:2027/28`);assert.equal(membership.status,'complete');assert.equal(membership.clubCount,22);assert.equal(new Set(membership.clubs.map(c=>c.id)).size,22);}const stepSix=career.worldMemberships.find(r=>r.key==='eng-national-league-step-five:2027/28');assert.equal(stepSix.status,'incomplete-step-six-feeder');assert.equal(stepSix.clubCount,288);assert.equal(stepSix.targetClubCount,320);assert.equal(stepSix.missingPromotionSlots,32);assert.equal(stepSix.relegatedToStepSixClubIds.length,32);const boundary=career.worldBoundaries.find(r=>r.key==='english-pyramid:2027/28');assert.equal(boundary.status,'step-four-ready-step-six-boundary');assert.equal(boundary.stepFourStatus,'complete');assert.equal(boundary.stepFiveStatus,'incomplete-step-six-feeder');});

test('derived 2027/28 Step 4 season completes 2028/29 Step 3 membership',()=>{const career=careerFixture(),db=dbFixture();finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});assert.equal(rolloverPremierLeagueSeason(career,{db}).status,'rolled-over');const result=completeActiveSeason(career);for(const division of Object.values(result.stepFourDivisions))assert.ok(['finalised','already-finalised'].includes(division.status));const aggregate=career.worldMemberships.find(r=>r.key==='eng-national-league-step-three:2028/29');assert.equal(aggregate.status,'complete');assert.equal(aggregate.clubCount,88);assert.equal(aggregate.promotedFromStepFourClubIds.length,16);});

test('Step 5 feeder unlocks a legitimate Premier League rollover into START 2034/35',()=>{const career=careerFixture(),db=dbFixture();finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});for(const expectedSeason of ['2027/28','2028/29','2029/30','2030/31','2031/32','2032/33','2033/34']){assert.equal(rolloverPremierLeagueSeason(career,{db}).status,'rolled-over');assert.equal(career.season,expectedSeason);completeActiveSeason(career);}const validation=validatePremierLeagueRollover(career,db);assert.equal(validation.ok,true);assert.equal(validation.sourceSeason,'2033/34');assert.equal(validation.targetSeason,'2034/35');assert.equal(rolloverPremierLeagueSeason(career,{db}).status,'rolled-over');assert.equal(career.season,'2034/35');assert.equal(career.seasonClubIds.length,20);assert.equal(new Set(career.seasonClubIds).size,20);});
