import test from 'node:test';
import assert from 'node:assert/strict';
import { finaliseSeason } from '../season-finalisation-v10.js';
import { rolloverPremierLeagueSeason } from '../premier-league-rollover-v3.js';
import { PROCEDURAL_LOWER_FEEDER_POOL_SIZE, proceduralLowerFeederSnapshot } from '../procedural-lower-feeder-v1.js';
import { NATIONAL_LEAGUE_NORTH_ID, NATIONAL_LEAGUE_SOUTH_ID } from '../national-league-step-two-world-v1.js';

const clubIds=()=>Array.from({length:20},(_,i)=>`v10-pl-${String(i+1).padStart(2,'0')}`);
function fixtures(ids){const matches=[];let serial=0;for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++){matches.push({id:`v10-${++serial}-a`,played:true,homeClubId:ids[a],awayClubId:ids[b],homeGoals:1,awayGoals:0});matches.push({id:`v10-${++serial}-b`,played:true,homeClubId:ids[b],awayClubId:ids[a],homeGoals:0,awayGoals:1});}return[matches];}
function table(ids,protectedId){const ordered=[protectedId,...ids.filter(id=>id!==protectedId)];return ordered.map((clubId,index)=>({clubId,played:38,won:Math.max(1,29-index),drawn:3,lost:6+index,goalsFor:90-index,goalsAgainst:30+index,goalDifference:60-index*2,points:100-index*4}));}
function dbFixture(){const ids=clubIds(),clubs=ids.map((id,index)=>({id,name:`V10 Premier Club ${index+1}`,shortName:`V10 ${index+1}`,providerName:`V10 Premier Club ${index+1}`,countryCode:'ENG',leagueId:'eng-premier-league',venue:`Ground ${index+1}`,reputation:7100-index*20,isPlaceholder:false})),shape=[['GK','GK'],['DEF','DR'],['DEF','DC'],['DEF','DC'],['DEF','DL'],['MID','DMC'],['MID','MC'],['MID','AMC'],['ATT','AMR'],['ATT','ST'],['ATT','AML']],players=clubs.flatMap((club,ci)=>shape.map(([positionGroup,primaryPosition],pi)=>({id:`${club.id}-p${pi+1}`,name:`${club.name} Player ${pi+1}`,clubId:club.id,positionGroup,primaryPosition,currentAbility:137+(20-ci)+(pi%3),potentialAbility:165,isPlaceholder:false})));return{clubs,players};}
function careerFixture(){const ids=clubIds();return{version:2,id:'pyramid-v10-career',seed:'pyramid-v10-seed',managerName:'V10 Manager',clubId:ids[0],leagueId:'eng-premier-league',competitionId:'eng-premier-league',competitionName:'Premier League',season:'2026/27',status:'complete',roundIndex:38,fixtures:fixtures(ids),table:table(ids,ids[0]),seasonClubs:ids.map((id,index)=>({id,name:`V10 Premier Club ${index+1}`,strength:82-index*.4})),seasonClubIds:ids,seasonHistory:[],worldHistory:[],lowerLeagueHistory:[],worldMemberships:[],worldBoundaries:[],seasonEndDate:'2027-05-30',currentDate:'2027-05-30',lastMatch:{date:'2027-05-30'},calendar:{currentDate:'2027-05-30',fixturesReleased:true},preseason:{phase:'complete'},worldClock:{schemaVersion:2,season:'2026/27',acknowledgedMilestones:[],history:[],totalDaysAdvanced:300},tactics:{formation:'4-3-3',mentality:'Balanced',pressing:'Standard'},lineupIds:Array.from({length:11},(_,index)=>`${ids[0]}-p${index+1}`),playerStatus:{}};}
function completeActiveSeason(career){const ids=[...career.seasonClubIds];career.table=table(ids,career.clubId);career.fixtures=career.fixtures.map(round=>round.map(match=>({...match,played:true,homeGoals:1,awayGoals:0})));career.status='complete';career.roundIndex=38;career.currentDate=career.seasonEndDate;career.calendar.currentDate=career.seasonEndDate;career.lastMatch={date:career.seasonEndDate};return finaliseSeason(career,{completedAt:`${career.seasonEndDate}T18:00:00.000Z`});}
function nextSeason(label){const start=Number(label.slice(0,4))+1;return `${start}/${String((start+1)%100).padStart(2,'0')}`;}
function assertCoreMembership(career,season){for(const id of [NATIONAL_LEAGUE_NORTH_ID,NATIONAL_LEAGUE_SOUTH_ID]){const record=career.worldMemberships.find(item=>item.key===`${id}:${season}`);assert.ok(record,`missing ${id} ${season}`);assert.equal(record.status,'complete');assert.equal(record.clubCount,24);assert.equal(new Set(record.clubs.map(c=>c.id)).size,24);}const aggregate=career.worldMemberships.find(item=>item.key===`eng-national-league-step-two:${season}`);assert.equal(aggregate.status,'complete');assert.equal(aggregate.clubCount,48);assert.equal(new Set(aggregate.clubs.map(c=>c.id)).size,48);}

test('procedural lower feeder replaces the Step 3 dependency with a persistent 88-club no-fixture pool',()=>{const career=careerFixture(),result=finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});assert.equal(result.status,'finalised');assert.equal(result.corePyramidStatus,'complete-through-national-league-north-south');assertCoreMembership(career,'2027/28');const snapshot=proceduralLowerFeederSnapshot(career);assert.equal(snapshot.poolSize,PROCEDURAL_LOWER_FEEDER_POOL_SIZE);assert.equal(snapshot.historyCount,1);assert.equal(snapshot.mode,'persistent-pool-no-fixtures');assert.equal('fixtures' in career.lowerFeederState,false);assert.equal('table' in career.lowerFeederState,false);const repeat=finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});assert.equal(repeat.status,'already-finalised');assert.equal(career.lowerFeederState.history.length,1);});

test('core English pyramid remains valid for the entire 40-season career without Step 3-7 simulation',()=>{const career=careerFixture(),db=dbFixture();let result=finaliseSeason(career,{completedAt:'2027-05-30T18:00:00.000Z'});assert.equal(result.corePyramidStatus,'complete-through-national-league-north-south');assertCoreMembership(career,'2027/28');let current='2026/27';for(let seasonNumber=2;seasonNumber<=40;seasonNumber++){const target=nextSeason(current),rollover=rolloverPremierLeagueSeason(career,{db});assert.equal(rollover.status,'rolled-over',`rollover failed into ${target}`);assert.equal(career.season,target);result=completeActiveSeason(career);assert.equal(result.status,'finalised',`finalisation failed in ${target}`);assert.equal(result.corePyramidStatus,'complete-through-national-league-north-south');assertCoreMembership(career,nextSeason(target));const snapshot=proceduralLowerFeederSnapshot(career);assert.equal(snapshot.poolSize,88);assert.equal(new Set(snapshot.clubs.map(c=>c.id)).size,88);assert.equal(snapshot.historyCount,seasonNumber);current=target;}assert.equal(career.season,'2065/66');assert.equal(career.careerLifecycle.status,'retired');assert.equal(career.careerSummary.seasonsCompleted,40);assert.equal(career.lowerFeederState.history.length,40);const blocked=rolloverPremierLeagueSeason(career,{db});assert.ok(['career-complete','career-limit-reached'].includes(blocked.status));assert.notEqual(career.season,'2066/67');});
